spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mybatis
    driver-class-name: org.postgresql.Driver
    username: admin
    password: 5834
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    auto-mapping-unknown-column-behavior: none
    auto-mapping-behavior: full
  type-aliases-package: ru.imatveev.mybatistest.domain.entity
